/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-102062-g63b2b0f47d-ffmpeg-windows-build-helpers"
#endif /* AVUTIL_FFVERSION_H */
